=== ddradar/ddradar-old/song-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://ddradar.app/song-schema.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "Song Info",
    "required": [
      "id",
      "name",
      "nameKana",
      "nameIndex",
      "artist",
      "series",
      "minBPM",
      "maxBPM",
      "version"
    ],
    "properties": {
      "id": {
        "$id": "#/items/properties/id",
        "type": "string",
        "title": "Song's Id",
        "minLength": 32,
        "maxLength": 32,
        "examples": ["b1do8OI6qDDlQO0PI16868ql6bdbI886"],
        "pattern": "^([01689bdiloqDIOPQ]*)$"
      },
      "name": {
        "$id": "#/items/properties/name",
        "type": "string",
        "title": "Song Name",
        "examples": ["Splash Gold"],
        "pattern": "^(.*)$"
      },
      "nameKana": {
        "$id": "#/items/properties/nameKana",
        "type": "string",
        "title": "Name Furigana",
        "examples": ["SPLASH GOLD"],
        "pattern": "^([A-Z0-9 .ぁ-んー]*)$"
      },
      "nameIndex": {
        "$id": "#/items/properties/nameIndex",
        "type": "integer",
        "title": "Use for Sort by Name (あ:0, か:1, ..., わ:9, A:10, B:11, ..., Z:35, other:36)",
        "minimum": 0,
        "maximum": 36
      },
      "artist": {
        "$id": "#/items/properties/artist",
        "type": "string",
        "title": "Artist Name",
        "pattern": "^(.*)$"
      },
      "series": {
        "$id": "#/items/properties/series",
        "type": "string",
        "title": "Series title",
        "enum": [
          "1st",
          "2ndMIX",
          "3rdMIX",
          "4thMIX",
          "5thMIX",
          "DDRMAX",
          "DDRMAX2",
          "EXTREME",
          "SuperNOVA",
          "SuperNOVA2",
          "X",
          "X2",
          "X3 VS 2ndMIX",
          "2013",
          "2014",
          "A",
          "A20"
        ],
        "default": "A20",
        "pattern": "^(.*)$"
      },
      "minBPM": {
        "$id": "#/items/properties/minBPM",
        "type": ["integer", "null"],
        "title": "Min BPM (if ???-???, set null)",
        "examples": [100, null]
      },
      "maxBPM": {
        "$id": "#/items/properties/maxBPM",
        "type": ["integer", "null"],
        "title": "Max BPM  (if ???-???, set null)",
        "examples": [400, null]
      },
      "version": {
        "$id": "#/items/properties/version",
        "type": "integer",
        "title": "Use for diff update. if you change or create data, increase its version."
      }
    }
  }
}

=== ddradar/ddradar-old/song-info/data/songs/song-4th.json
[
  {
    "id": "6Qq1q91q8iIPlI89qDq96bO8QDD0qOql",
    "name": "B4U",
    "nameKana": "B4U",
    "nameIndex": 11,
    "artist": "NAOKI",
    "series": "4thMIX",
    "minBPM": 155,
    "maxBPM": 155,
    "version": 20190320
  },
  {
    "id": "P8P1dlqi9D111iIDPOP0l9DIO1l6lqO9",
    "name": "BABY BABY GIMME YOUR LOVE",
    "nameKana": "BABY BABY GIMME YOUR LOVE",
    "nameIndex": 11,
    "artist": "DIVAS",
    "series": "4thMIX",
    "minBPM": 96,
    "maxBPM": 96,
    "version": 20190320
  },
  {
    "id": "ii6Oooool0IoOqi1qdDo96QIil6IoOq0",
    "name": "BURNIN' THE FLOOR",
    "nameKana": "BURNIN THE FLOOR",
    "nameIndex": 11,
    "artist": "NAOKI",
    "series": "4thMIX",
    "minBPM": 155,
    "maxBPM": 155,
    "version": 20190320
  },
  {
    "id": "ioi6db99oOPPDd1db888D6oi6bb06o0P",
    "name": "CAN'T STOP FALLIN' IN LOVE",
    "nameKana": "CANT STOP FALLIN IN LOVE",
    "nameIndex": 12,
    "artist": "NAOKI",
    "series": "4thMIX",
    "minBPM": 155,
    "maxBPM": 155,
    "version": 20190320
  },
  {
    "id": "i0bdP6II6dqb6lbQQ9q9OQq68i1qPddO",
    "name": "CELEBRATE NITE",
    "nameKana": "CELEBRATE NITE",
    "nameIndex": 12,
    "artist": "N.M.R",
    "series": "4thMIX",
    "minBPM": 144,
    "maxBPM": 144,
    "version": 20190320
  },
  {
    "id": "1q6obddbql8lQdPI19liD6PdQ0dPIODd",
    "name": "Don't Stop!～AMD 2nd MIX～",
    "nameKana": "DONT STOP AMD 2ND MIX",
    "nameIndex": 13,
    "artist": "Dr.VIBE feat. JP Miles",
    "series": "4thMIX",
    "minBPM": 130,
    "maxBPM": 130,
    "version": 20190320
  },
  {
    "id": "Q0OiPQQ8IbIDq08IO9Io0qDdoDPPdd1q",
    "name": "DROP OUT",
    "nameKana": "DROP OUT",
    "nameIndex": 13,
    "artist": "NW260",
    "series": "4thMIX",
    "minBPM": 260,
    "maxBPM": 260,
    "version": 20190320
  },
  {
    "id": "D81Pq66DQPiQdliqIPl0ioPOi9OlQoQ9",
    "name": "era (nostalmix)",
    "nameKana": "ERA NOSTALMIX",
    "nameIndex": 14,
    "artist": "TaQ",
    "series": "4thMIX",
    "minBPM": 90,
    "maxBPM": 180,
    "version": 20190320
  },
  {
    "id": "O1blDPOQ8IQb00o0D89QIDIlo8b06liD",
    "name": "HIGHER",
    "nameKana": "HIGHER",
    "nameIndex": 17,
    "artist": "NM feat. SUNNY",
    "series": "4thMIX",
    "minBPM": 132,
    "maxBPM": 132,
    "version": 20190320
  },
  {
    "id": "ODq019O9o1OPdq9PiPl0o8D8DQ8bid88",
    "name": "Holic",
    "nameKana": "HOLIC",
    "nameIndex": 17,
    "artist": "TaQ",
    "series": "4thMIX",
    "minBPM": 155,
    "maxBPM": 155,
    "version": 20190320
  },
  {
    "id": "8l808Do60DP0qDbD066QQqP1qOQdob90",
    "name": "HYSTERIA",
    "nameKana": "HYSTERIA",
    "nameIndex": 17,
    "artist": "NAOKI 190",
    "series": "4thMIX",
    "minBPM": 190,
    "maxBPM": 190,
    "version": 20190320
  },
  {
    "id": "8lDOiqP0biD8dD9lOQO619i1PqbqDiP8",
    "name": "LEADING CYBER",
    "nameKana": "LEADING CYBER",
    "nameIndex": 21,
    "artist": "dj TAKA",
    "series": "4thMIX",
    "minBPM": 150,
    "maxBPM": 150,
    "version": 20190320
  },
  {
    "id": "boOdPIqbDd8li0O0IqliPo1Doq99Ob09",
    "name": "LOVE AGAIN TONIGHT～For Melissa MIX～",
    "nameKana": "LOVE AGAIN TONIGHT FOR MELISSA MIX",
    "nameIndex": 21,
    "artist": "NAOKI feat. PAULA TERRY",
    "series": "4thMIX",
    "minBPM": 150,
    "maxBPM": 150,
    "version": 20190320
  },
  {
    "id": "6Ddo196olOPi9IQdbQ8Qbd8do8Q1obOD",
    "name": "MY SUMMER LOVE",
    "nameKana": "MY SUMMER LOVE",
    "nameIndex": 22,
    "artist": "MITSU-O! with GEILA",
    "series": "4thMIX",
    "minBPM": 100,
    "maxBPM": 100,
    "version": 20190320
  },
  {
    "id": "1d10660Dd0IOibDI890Ild80q6ddoQO8",
    "name": "ORION.78(AMeuro-MIX)",
    "nameKana": "ORION78 AMEURO MIX",
    "nameIndex": 24,
    "artist": "RE-VENGE",
    "series": "4thMIX",
    "minBPM": 105,
    "maxBPM": 105,
    "version": 20190320
  },
  {
    "id": "DPQo8Q0l9D8IPiDiq11l8OI6i11OOb6O",
    "name": "PARANOIA EVOLUTION",
    "nameKana": "PARANOIA EVOLUTION",
    "nameIndex": 25,
    "artist": "200",
    "series": "4thMIX",
    "minBPM": 200,
    "maxBPM": 200,
    "version": 20190320
  },
  {
    "id": "60QoP9DoIo90D616989Q0D0iodOoOd91",
    "name": "SEXY PLANET",
    "nameKana": "SEXY PLANET",
    "nameIndex": 28,
    "artist": "Crystal Aliens",
    "series": "4thMIX",
    "minBPM": 180,
    "maxBPM": 180,
    "version": 20190320
  },
  {
    "id": "88do8dl8O6Ql1Qlb981lOi8D86oiq91P",
    "name": "SUPER STAR",
    "nameKana": "SUPER STAR",
    "nameIndex": 28,
    "artist": "D.J.RICH feat. TAILBROS.",
    "series": "4thMIX",
    "minBPM": 128,
    "maxBPM": 128,
    "version": 20190320
  },
  {
    "id": "D81D8689llDiOqPq0IP19bbQQiioPl8d",
    "name": "TRIP MACHINE CLIMAX",
    "nameKana": "TRIP MACHINE CLIMAX",
    "nameIndex": 29,
    "artist": "DE-SIRE",
    "series": "4thMIX",
    "minBPM": 180,
    "maxBPM": 180,
    "version": 20190320
  },
  {
    "id": "01808Q1Q6lQQ1lP0qd80I0b0qqDd1OOP",
    "name": "WILD RUSH",
    "nameKana": "WILD RUSH",
    "nameIndex": 32,
    "artist": "FACTOR-X",
    "series": "4thMIX",
    "minBPM": 80,
    "maxBPM": 180,
    "version": 20190320
  },
  {
    "id": "IQ0dIiDql9Q68d9ddQIiQbq1OPq8Db69",
    "name": ".59",
    "nameKana": ".59",
    "nameIndex": 36,
    "artist": "dj TAKA",
    "series": "4thMIX",
    "minBPM": 135,
    "maxBPM": 135,
    "version": 20190320
  }
]

=== ddradar/ddradar-old/song-info/data/songs/song-5th.json
[
  {
    "id": "doIiQl6oDPP6i9qobqoobblPQqPiI9bD",
    "name": "サナ・モレッテ・ネ・エンテ",
    "nameKana": "さな もれって ね えんて",
    "nameIndex": 2,
    "artist": "Togo Project feat. Sana",
    "series": "5thMIX",
    "minBPM": 90,
    "maxBPM": 90,
    "version": 20190320
  },
  {
    "id": "qdi88l6bo1Iqi9Qiqli8lIQQIPO1doQ9",
    "name": "ABSOLUTE",
    "nameKana": "ABSOLUTE",
    "nameIndex": 10,
    "artist": "dj TAKA",
    "series": "5thMIX",
    "minBPM": 144,
    "maxBPM": 144,
    "version": 20190320
  },
  {
    "id": "Q0qQO0P8818lIoo0boO66O0qd09dIlO8",
    "name": "Abyss",
    "nameKana": "ABYSS",
    "nameIndex": 10,
    "artist": "dj TAKA",
    "series": "5thMIX",
    "minBPM": 142,
    "maxBPM": 142,
    "version": 20190320
  },
  {
    "id": "18911Q6o6do9Dd1blIo6IliPd0PPb99i",
    "name": "AFRONOVA PRIMEVAL",
    "nameKana": "AFRONOVA PRIMEVAL",
    "nameIndex": 10,
    "artist": "8 bit",
    "series": "5thMIX",
    "minBPM": 200,
    "maxBPM": 200,
    "version": 20190320
  },
  {
    "id": "iIP09bOq1l1b9b1l011IDIQ6Iill90Io",
    "name": "BROKEN MY HEART",
    "nameKana": "BROKEN MY HEART",
    "nameIndex": 11,
    "artist": "NAOKI feat. PAULA TERRY",
    "series": "5thMIX",
    "minBPM": 160,
    "maxBPM": 160,
    "version": 20190320
  },
  {
    "id": "DOqPd1Iid6oObd8i96I9oo8obbODb96o",
    "name": "CAN'T STOP FALLIN' IN LOVE ～SPEED MIX～",
    "nameKana": "CANT STOP FALLIN IN LOVE SPEED MIX",
    "nameIndex": 12,
    "artist": "NAOKI",
    "series": "5thMIX",
    "minBPM": 170,
    "maxBPM": 170,
    "version": 20190320
  },
  {
    "id": "QDP0i688bQi1Idqil1dOqDdPdoIPP6Q0",
    "name": "DXY!",
    "nameKana": "DXY",
    "nameIndex": 13,
    "artist": "TaQ",
    "series": "5thMIX",
    "minBPM": 148,
    "maxBPM": 148,
    "version": 20190320
  },
  {
    "id": "bPD6ObloQPOOiQb1DbQDdilodiddlIlb",
    "name": "ECSTASY",
    "nameKana": "ECSTASY",
    "nameIndex": 14,
    "artist": "d-complex",
    "series": "5thMIX",
    "minBPM": 145,
    "maxBPM": 145,
    "version": 20190320
  },
  {
    "id": "IPi69l86oqdDd8qoll61166D8969869I",
    "name": "Electro Tuned ( the SubS Mix )",
    "nameKana": "ELECTRO TUNED THE SUBS MIX",
    "nameIndex": 14,
    "artist": "TaQ",
    "series": "5thMIX",
    "minBPM": 125,
    "maxBPM": 125,
    "version": 20190320
  },
  {
    "id": "qIDI69oIo8OlQqdqqDilI1do6IbP16Q6",
    "name": "Healing Vision",
    "nameKana": "HEALING VISION",
    "nameIndex": 17,
    "artist": "DE-SIRE",
    "series": "5thMIX",
    "minBPM": 49,
    "maxBPM": 196,
    "version": 20190320
  },
  {
    "id": "6oldqOoilo1OoP6P9OoO8bdD9lI86qdQ",
    "name": "INSERTiON",
    "nameKana": "INSERTION",
    "nameIndex": 18,
    "artist": "NAOKI underground",
    "series": "5thMIX",
    "minBPM": 110,
    "maxBPM": 225,
    "version": 20190320
  },
  {
    "id": "PP1q0iii1D6Dq9QOd0qqDOQD0160QoPD",
    "name": "PARANOiA ETERNAL",
    "nameKana": "PARANOIA ETERNAL",
    "nameIndex": 25,
    "artist": "STM 200",
    "series": "5thMIX",
    "minBPM": 200,
    "maxBPM": 200,
    "version": 20190320
  },
  {
    "id": "Qb90bo6I0Pd9181iIoOPoqPOOOQq6dQ1",
    "name": "STILL IN MY HEART",
    "nameKana": "STILL IN MY HEART",
    "nameIndex": 28,
    "artist": "NAOKI",
    "series": "5thMIX",
    "minBPM": 150,
    "maxBPM": 150,
    "version": 20190320
  }
]

=== ddradar/ddradar-old/song-info/data/songs/song-max2.json
[
  {
    "id": "l9lq19DdiD8qQPoPOlboi1qQii0IQI86",
    "name": "革命",
    "nameKana": "かくめい",
    "nameIndex": 1,
    "artist": "dj TAKA with NAOKI",
    "series": "DDRMAX2",
    "minBPM": 83,
    "maxBPM": 148,
    "version": 20191109
  },
  {
    "id": "DdO1iboqI6980Q6QPD9P1PbQQ88I16lq",
    "name": "AFRONOVA(FROM NONSTOP MEGAMIX)",
    "nameKana": "AFRONOVA FROM NONSTOP MEGAMIX",
    "nameIndex": 10,
    "artist": "RE-VENGE",
    "series": "DDRMAX2",
    "minBPM": 200,
    "maxBPM": 200,
    "version": 20191109
  },
  {
    "id": "808dq8OIq16PP19i1bP0IDP1OqPOlo6q",
    "name": "AM-3P(AM EAST mix)",
    "nameKana": "AM 3P AM EAST MIX",
    "nameIndex": 10,
    "artist": "KTz",
    "series": "DDRMAX2",
    "minBPM": 140,
    "maxBPM": 140,
    "version": 20191109
  },
  {
    "id": "POIDil00didIo98D10loIObibPOob88O",
    "name": "B4U(B4 ZA BEAT MIX)",
    "nameKana": "B4U B4 ZA BEAT MIX",
    "nameIndex": 11,
    "artist": "NAOKI",
    "series": "DDRMAX2",
    "minBPM": 170,
    "maxBPM": 170,
    "version": 20191109
  },
  {
    "id": "bqQ1OQDidQD8QbIqql06O6o1QD6oOodP",
    "name": "BRE∀K DOWN!",
    "nameKana": "BREAK DOWN",
    "nameIndex": 11,
    "artist": "BeForU",
    "series": "DDRMAX2",
    "minBPM": 190,
    "maxBPM": 190,
    "version": 20191109
  },
  {
    "id": "i18OPo6l8Q6bo9q0qP6889IDqoP8O0Qq",
    "name": "BRILLIANT 2U(K.O.G G3 MIX)",
    "nameKana": "BRILLIANT 2U KOG G3 MIX",
    "nameIndex": 11,
    "artist": "NAOKI",
    "series": "DDRMAX2",
    "minBPM": 170,
    "maxBPM": 170,
    "version": 20191109
  },
  {
    "id": "QdbPPPDlIQiI191qPdblO01O8P8o6D68",
    "name": "BURNIN' THE FLOOR (BLUE FIRE mix)",
    "nameKana": "BURNIN THE FLOOR BLUE FIRE MIX",
    "nameIndex": 11,
    "artist": "NAOKI",
    "series": "DDRMAX2",
    "minBPM": 155,
    "maxBPM": 155,
    "version": 20191109
  },
  {
    "id": "i86qD6Pl61dPI0Q9db1P8bl1ii99q1lD",
    "name": "BURNING HEAT! (3 Option MIX)",
    "nameKana": "BURNING HEAT 3 OPTION MIX",
    "nameIndex": 11,
    "artist": "Mr.T with Motoaki. F",
    "series": "DDRMAX2",
    "minBPM": 166,
    "maxBPM": 166,
    "version": 20191109
  },
  {
    "id": "1Qqo9bID18OdiI1Qb0lP9DIqIO6ldPOP",
    "name": "CANDY♥",
    "nameKana": "CANDY HEART",
    "nameIndex": 12,
    "artist": "小坂りゆ",
    "series": "DDRMAX2",
    "minBPM": 180,
    "maxBPM": 180,
    "version": 20191109
  },
  {
    "id": "O6q1o06Po9lQbqOl08Io1obqQ9QPi09b",
    "name": "CELEBRATE NITE(EURO TRANCE STYLE)",
    "nameKana": "CELEBRATE NITE EURO TRANCE STYLE",
    "nameIndex": 12,
    "artist": "N.M.R",
    "series": "DDRMAX2",
    "minBPM": 144,
    "maxBPM": 144,
    "version": 20191109
  },
  {
    "id": "iQo0QOoI6bOPQlbb9ldOo9lbdD1idiOO",
    "name": "D2R",
    "nameKana": "D2R",
    "nameIndex": 13,
    "artist": "NAOKI",
    "series": "DDRMAX2",
    "minBPM": 160,
    "maxBPM": 160,
    "version": 20191109
  },
  {
    "id": "98q8616ddDIqdo1dbqbO0Po96oldo1Oo",
    "name": "DESTINY",
    "nameKana": "DESTINY",
    "nameIndex": 13,
    "artist": "NAOKI feat. PAULA TERRY",
    "series": "DDRMAX2",
    "minBPM": 155,
    "maxBPM": 155,
    "version": 20191109
  },
  {
    "id": "8Pb6oPdbO6lo8lbiQ181IDidI9ll8q80",
    "name": "DIVE TO THE NIGHT",
    "nameKana": "DIVE TO THE NIGHT",
    "nameIndex": 13,
    "artist": "小坂りゆ",
    "series": "DDRMAX2",
    "minBPM": 155,
    "maxBPM": 155,
    "version": 20191109
  },
  {
    "id": "d0P01d9q8oOd8OP1bQPoqlq96906PqPD",
    "name": "DROP OUT(FROM NONSTOP MEGAMIX)",
    "nameKana": "DROP OUT FROM NONSTOP MEGAMIX",
    "nameIndex": 13,
    "artist": "NW260",
    "series": "DDRMAX2",
    "minBPM": 130,
    "maxBPM": 130,
    "version": 20191109
  },
  {
    "id": "Dd6lP00DPqIb0d6iqOdlO08l69l6q1di",
    "name": "ECSTASY (midnight blue mix)",
    "nameKana": "ECSTASY MIDNIGHT BLUE MIX",
    "nameIndex": 14,
    "artist": "d-complex",
    "series": "DDRMAX2",
    "minBPM": 145,
    "maxBPM": 145,
    "version": 20191109
  },
  {
    "id": "8DQDq16PPlli6o9iDl11DqooqOPlOb08",
    "name": "HIGHER (next morning mix)",
    "nameKana": "HIGHER NEXT MORNING MIX",
    "nameIndex": 17,
    "artist": "NM feat. SUNNY",
    "series": "DDRMAX2",
    "minBPM": 132,
    "maxBPM": 132,
    "version": 20191109
  },
  {
    "id": "lPloI86odlIbIo96P169b9I0Ob8lD189",
    "name": "HYSTERIA 2001",
    "nameKana": "HYSTERIA 2001",
    "nameIndex": 17,
    "artist": "NM",
    "series": "DDRMAX2",
    "minBPM": 190,
    "maxBPM": 190,
    "version": 20191109
  },
  {
    "id": "DddIPd6iId8Doqq8OibDlD1dOi8PO8o9",
    "name": "i feel ...",
    "nameKana": "I FEEL",
    "nameIndex": 18,
    "artist": "AKIRA YAMAOKA",
    "series": "DDRMAX2",
    "minBPM": 141,
    "maxBPM": 141,
    "version": 20191109
  },
  {
    "id": "lObPDQDI08DoodDq1061IP1qbQ1qQQbl",
    "name": "MAXX UNLIMITED",
    "nameKana": "MAXX UNLIMITED",
    "nameIndex": 22,
    "artist": "Z",
    "series": "DDRMAX2",
    "minBPM": 140,
    "maxBPM": 320,
    "version": 20191109
  },
  {
    "id": "d99P0I1i960QO0oolD6oQIO8OObO9Plb",
    "name": "MY SUMMER LOVE(TOMMY'S SMILE MIX)",
    "nameKana": "MY SUMMER LOVE TOMMYS SMILE MIX",
    "nameIndex": 22,
    "artist": "MITSU-O! with GEILA",
    "series": "DDRMAX2",
    "minBPM": 100,
    "maxBPM": 100,
    "version": 20191109
  },
  {
    "id": "Qo9l6l6lq0q618bQOb8d6qiooiiPQqoI",
    "name": "rain of sorrow",
    "nameKana": "RAIN OF SORROW",
    "nameIndex": 27,
    "artist": "NM feat. EBONY FAY",
    "series": "DDRMAX2",
    "minBPM": 140,
    "maxBPM": 140,
    "version": 20191109
  },
  {
    "id": "Db9D6Old6lIo01q0qlQ0dD1oDdbdob8I",
    "name": "Secret Rendez-vous",
    "nameKana": "SECRET RENDEZ VOUS",
    "nameIndex": 28,
    "artist": "DIVAS",
    "series": "DDRMAX2",
    "minBPM": 98,
    "maxBPM": 98,
    "version": 20191109
  },
  {
    "id": "O06Id8PIDbDblO109ddi1dldd0bqDdQ1",
    "name": "SEXY PLANET(FROM NONSTOP MEGAMIX)",
    "nameKana": "SEXY PLANET FROM NONSTOP MEGAMIX",
    "nameIndex": 28,
    "artist": "Crystal Aliens",
    "series": "DDRMAX2",
    "minBPM": 180,
    "maxBPM": 180,
    "version": 20191109
  },
  {
    "id": "oio6bqP08PPoP9qIq1oi9Dib9PIq9l11",
    "name": "Silent Hill (3rd christmas mix)",
    "nameKana": "SILENT HILL 3RD CHRISTMAS MIX",
    "nameIndex": 28,
    "artist": "THOMAS HOWARD",
    "series": "DDRMAX2",
    "minBPM": 125,
    "maxBPM": 125,
    "version": 20191109
  },
  {
    "id": "DOOb99dlP8PdIbDOQIqoqll60Iob9189",
    "name": "STILL IN MY HEART (MOMO MIX)",
    "nameKana": "STILL IN MY HEART MOMO MIX",
    "nameIndex": 28,
    "artist": "NAOKI",
    "series": "DDRMAX2",
    "minBPM": 85,
    "maxBPM": 170,
    "version": 20191109
  },
  {
    "id": "0qQ1odlooiQO99DDP6bD9bOq89669PQb",
    "name": "SUPER STAR(FROM NONSTOP MEGAMIX)",
    "nameKana": "SUPER STAR FROM NONSTOP MEGAMIX",
    "nameIndex": 28,
    "artist": "D.J.RICH feat. TAILBROS.",
    "series": "DDRMAX2",
    "minBPM": 128,
    "maxBPM": 128,
    "version": 20191109
  },
  {
    "id": "8809ol0qbbd6919bbl0b8id1669PqQ08",
    "name": "Sweet Sweet ♥ Magic",
    "nameKana": "SWEET SWEET LOVE MAGIC",
    "nameIndex": 28,
    "artist": "jun",
    "series": "DDRMAX2",
    "minBPM": 180,
    "maxBPM": 180,
    "version": 20191109
  },
  {
    "id": "io688qld6Pqq6bI01q86illP18biq0bd",
    "name": "TSUGARU",
    "nameKana": "TSUGARU",
    "nameIndex": 29,
    "artist": "RevenG vs DE-SIRE",
    "series": "DDRMAX2",
    "minBPM": 165,
    "maxBPM": 165,
    "version": 20191109
  },
  {
    "id": "1qDD1DdPlId69010IQ18I6q8Q00IoI6D",
    "name": "TSUGARU (APPLE MIX)",
    "nameKana": "TSUGARU APPLE MIX",
    "nameIndex": 29,
    "artist": "RevenG vs DE-SIRE",
    "series": "DDRMAX2",
    "minBPM": 165,
    "maxBPM": 165,
    "version": 20191109
  },
  {
    "id": "ibOQ0QOdIPdIbIo0oPoDDI1DqPId00li",
    "name": "WILD RUSH(FROM NONSTOP MEGAMIX)",
    "nameKana": "WILD RUSH FROM NONSTOP MEGAMIX",
    "nameIndex": 32,
    "artist": "FACTOR-X",
    "series": "DDRMAX2",
    "minBPM": 125,
    "maxBPM": 125,
    "version": 20191109
  }
]

=== ddradar/ddradar-old/song-info/data/songs/song-max.json
[
  {
    "id": "OPbqldiq0dQIo1011086IOl1qbOloOl9",
    "name": "CANDY☆",
    "nameKana": "CANDY",
    "nameIndex": 12,
    "artist": "Luv UNLIMITED",
    "series": "DDRMAX",
    "minBPM": 192,
    "maxBPM": 192,
    "version": 20191109
  },
  {
    "id": "iOPbIi1b99819b9QiD8QbdPbq0DqO0DO",
    "name": "exotic ethnic",
    "nameKana": "EXOTIC ETHNIC",
    "nameIndex": 14,
    "artist": "RevenG",
    "series": "DDRMAX",
    "minBPM": 190,
    "maxBPM": 190,
    "version": 20191109
  },
  {
    "id": "olQQ8QPPqqObDD9ooodOl9i9od8b06I9",
    "name": "Healing Vision ～Angelic mix～",
    "nameKana": "HEALING VISION ANGELIC MIX",
    "nameIndex": 17,
    "artist": "2MB",
    "series": "DDRMAX",
    "minBPM": 46,
    "maxBPM": 196,
    "version": 20191109
  },
  {
    "id": "bP69QdDQ0QQ9dP0dDio0dO61i9Dbdl00",
    "name": "Let the beat hit em!(CLASSIC R&B STYLE)",
    "nameKana": "LET THE BEAT HIT EM CLASSIC R AND B STYLE",
    "nameIndex": 21,
    "artist": "Stone Bros.",
    "series": "DDRMAX",
    "minBPM": 102,
    "maxBPM": 102,
    "version": 20191109
  },
  {
    "id": "6P18lOliIQqIO6Di0PP8iDlDQ01b0o0q",
    "name": "MAX 300",
    "nameKana": "MAX 300",
    "nameIndex": 22,
    "artist": "Ω",
    "series": "DDRMAX",
    "minBPM": 300,
    "maxBPM": 300,
    "version": 20191109
  },
  {
    "id": "61ido0DPl8q0dI1i011Do1b6669dPIlo",
    "name": "ORION.78～civilization mix～",
    "nameKana": "ORION78 CIVILIZATION MIX",
    "nameIndex": 24,
    "artist": "2MB",
    "series": "DDRMAX",
    "minBPM": 200,
    "maxBPM": 200,
    "version": 20191109
  }
]

=== ddradar/ddradar-old/song-info/data/songs/song-1st.json
[
  {
    "id": "8Il6980di8P89lil1PDIqqIbiq1QO8lQ",
    "name": "MAKE IT BETTER",
    "nameKana": "MAKE IT BETTER",
    "nameIndex": 22,
    "artist": "mitsu-O!",
    "series": "1st",
    "minBPM": 119,
    "maxBPM": 119,
    "version": 20190320
  },
  {
    "id": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
    "name": "PARANOiA",
    "nameKana": "PARANOIA",
    "nameIndex": 25,
    "artist": "180",
    "series": "1st",
    "minBPM": 180,
    "maxBPM": 180,
    "version": 20190320
  },
  {
    "id": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
    "name": "TRIP MACHINE",
    "nameKana": "TRIP MACHINE",
    "nameIndex": 29,
    "artist": "DE-SIRE",
    "series": "1st",
    "minBPM": 160,
    "maxBPM": 160,
    "version": 20190320
  }
]

=== ddradar/ddradar-old/song-info/data/songs/song-3rd.json
[
  {
    "id": "Pd99DQo0bD9D9oIbPIId18P6l8qlDQO6",
    "name": "AFRONOVA",
    "nameKana": "AFRONOVA",
    "nameIndex": 10,
    "artist": "RE-VENGE",
    "series": "3rdMIX",
    "minBPM": 200,
    "maxBPM": 200,
    "version": 20190320
  },
  {
    "id": "Qo9P1oOoDQIoOb8Dd0PdOdoD1D1Pbd8D",
    "name": "AFTER THE GAME OF LOVE",
    "nameKana": "AFTER THE GAME OF LOVE",
    "nameIndex": 10,
    "artist": "NPD3",
    "series": "3rdMIX",
    "minBPM": 105,
    "maxBPM": 105,
    "version": 20190320
  },
  {
    "id": "di9ddbd1lb80q98ODdod0ODQ0q6PdQP1",
    "name": "CUTIE CHASER",
    "nameKana": "CUTIE CHASER",
    "nameIndex": 12,
    "artist": "CLUB SPICE",
    "series": "3rdMIX",
    "minBPM": 126,
    "maxBPM": 126,
    "version": 20190320
  },
  {
    "id": "P98dl8qdoilqbPqIO86ood601o1696D8",
    "name": "DEAD END",
    "nameKana": "DEAD END",
    "nameIndex": 13,
    "artist": "N & S",
    "series": "3rdMIX",
    "minBPM": 190,
    "maxBPM": 190,
    "version": 20190320
  },
  {
    "id": "8O0D9P6l9P9ooQdODioDIdQPq6DiDlbl",
    "name": "DROP THE BOMB",
    "nameKana": "DROP THE BOMB",
    "nameIndex": 13,
    "artist": "Scotty D.",
    "series": "3rdMIX",
    "minBPM": 150,
    "maxBPM": 150,
    "version": 20190320
  },
  {
    "id": "1QIPID18qib8D9Oo9lOo8I6DPi9qiod6",
    "name": "DYNAMITE RAVE",
    "nameKana": "DYNAMITE RAVE",
    "nameIndex": 13,
    "artist": "NAOKI",
    "series": "3rdMIX",
    "minBPM": 150,
    "maxBPM": 150,
    "version": 20190320
  },
  {
    "id": "q6qI6llb69D1IQq0OiP8OD06Qioob91Q",
    "name": "GRADIUSIC CYBER ～AMD G5 MIX～",
    "nameKana": "GRADIUSIC CYBER AMD G5 MIX",
    "nameIndex": 16,
    "artist": "BIG-O feat. TAKA",
    "series": "3rdMIX",
    "minBPM": 160,
    "maxBPM": 160,
    "version": 20190320
  },
  {
    "id": "901q61iP6lPiDqIQoQod9PDqlOPq1bb9",
    "name": "La Señorita",
    "nameKana": "LA SENORITA",
    "nameIndex": 21,
    "artist": "CAPTAIN.T",
    "series": "3rdMIX",
    "minBPM": 182,
    "maxBPM": 182,
    "version": 20190320
  },
  {
    "id": "boP0i08bqQ9d9OoP8Ol6I0l9Po01DiQb",
    "name": "La Señorita Virtual",
    "nameKana": "LA SENORITA VIRTUAL",
    "nameIndex": 21,
    "artist": "2MB",
    "series": "3rdMIX",
    "minBPM": 182,
    "maxBPM": 182,
    "version": 20190320
  },
  {
    "id": "i8II16blIIbQQd196b616OPbPO910oi9",
    "name": "LOVE THIS FEELIN'",
    "nameKana": "LOVE THIS FEELIN",
    "nameIndex": 21,
    "artist": "Chang ma",
    "series": "3rdMIX",
    "minBPM": 190,
    "maxBPM": 190,
    "version": 20190320
  },
  {
    "id": "0lDP0P06PIPl1iiIDOb919iqo1oPdlP8",
    "name": "PARANOiA Rebirth",
    "nameKana": "PARANOIA REBIRTH",
    "nameIndex": 25,
    "artist": "190'",
    "series": "3rdMIX",
    "minBPM": 190,
    "maxBPM": 190,
    "version": 20190320
  },
  {
    "id": "80bQi8IQ8o1iidqd6oQiDPQoPi909olq",
    "name": "Silent Hill",
    "nameKana": "SILENT HILL",
    "nameIndex": 28,
    "artist": "THOMAS HOWARD",
    "series": "3rdMIX",
    "minBPM": 125,
    "maxBPM": 125,
    "version": 20190320
  },
  {
    "id": "9lob1d1QPd9qiPlQOQ6l0dbodOoDPq1d",
    "name": "think ya better D",
    "nameKana": "THINK YA BETTER D",
    "nameIndex": 29,
    "artist": "sAmi",
    "series": "3rdMIX",
    "minBPM": 136,
    "maxBPM": 136,
    "version": 20190320
  },
  {
    "id": "qQ9Oo611P0dObD8q6O0Q968bbl8I91OO",
    "name": "TRIP MACHINE～luv mix～",
    "nameKana": "TRIP MACHINE LUV MIX",
    "nameIndex": 29,
    "artist": "2MB",
    "series": "3rdMIX",
    "minBPM": 160,
    "maxBPM": 160,
    "version": 20190320
  }
]

=== ddradar/ddradar-old/song-info/data/songs/song-2nd.json
[
  {
    "id": "dq190Il9iO1bD698ll6ddObIlqdIQ1O9",
    "name": "AM-3P",
    "nameKana": "AM 3P",
    "nameIndex": 10,
    "artist": "KTz",
    "series": "2ndMIX",
    "minBPM": 130,
    "maxBPM": 130,
    "version": 20190320
  },
  {
    "id": "DblIbDd6lQQQoO9bloOI9iIqO1IiQoID",
    "name": "BRILLIANT 2U",
    "nameKana": "BRILLIANT 2U",
    "nameIndex": 11,
    "artist": "NAOKI",
    "series": "2ndMIX",
    "minBPM": 150,
    "maxBPM": 150,
    "version": 20190320
  },
  {
    "id": "DbPodlqiOQdD88bo8lPO9D6iql1DO8P0",
    "name": "BRILLIANT 2U(Orchestra Groove)",
    "nameKana": "BRILLIANT 2U ORCHESTRA GROOVE",
    "nameIndex": 11,
    "artist": "NAOKI",
    "series": "2ndMIX",
    "minBPM": 150,
    "maxBPM": 150,
    "version": 20190320
  },
  {
    "id": "8liDbidQoI6Q01lO9iibIdboIiDl66Qo",
    "name": "e-motion",
    "nameKana": "E MOTION",
    "nameIndex": 14,
    "artist": "e.o.s",
    "series": "2ndMIX",
    "minBPM": 145,
    "maxBPM": 145,
    "version": 20190320
  },
  {
    "id": "Dq0Iio09Pb9iD0lbb0I0qd8Q8i10II09",
    "name": "GENOM SCREAMS",
    "nameKana": "GENOM SCREAMS",
    "nameIndex": 16,
    "artist": "L.E.D.LIGHT",
    "series": "2ndMIX",
    "minBPM": 150,
    "maxBPM": 150,
    "version": 20190320
  },
  {
    "id": "0lDDIlQ91lq6O16q9QQ681d6Db1l0oOb",
    "name": "KEEP ON MOVIN'",
    "nameKana": "KEEP ON MOVIN",
    "nameIndex": 20,
    "artist": "N.M.R",
    "series": "2ndMIX",
    "minBPM": 132,
    "maxBPM": 132,
    "version": 20190320
  },
  {
    "id": "9qP16D6l11i9P1lQ0b1DIqoOqqiIQDl9",
    "name": "MAKE IT BETTER (So-REAL Mix)",
    "nameKana": "MAKE IT BETTER SO REAL MIX",
    "nameIndex": 22,
    "artist": "mitsu-O!SUMMER",
    "series": "2ndMIX",
    "minBPM": 118,
    "maxBPM": 118,
    "version": 20190320
  },
  {
    "id": "9doPbId8qid9I9l6ooloPQD1lq1Plb6I",
    "name": "PARANOiA KCET ～clean mix～",
    "nameKana": "PARANOIA KCET CLEAN MIX",
    "nameIndex": 25,
    "artist": "2MB",
    "series": "2ndMIX",
    "minBPM": 180,
    "maxBPM": 180,
    "version": 20190320
  },
  {
    "id": "Pl0dPid9lQDo6PDQDqPboPqO6iIDIqoo",
    "name": "PARANOiA MAX～DIRTY MIX～",
    "nameKana": "PARANOIA MAX DIRTY MIX",
    "nameIndex": 25,
    "artist": "190",
    "series": "2ndMIX",
    "minBPM": 190,
    "maxBPM": 190,
    "version": 20190320
  },
  {
    "id": "DQlQ1DlPbq900oqdOo8l0d6I1lIOl99l",
    "name": "PUT YOUR FAITH IN ME",
    "nameKana": "PUT YOUR FAITH IN ME",
    "nameIndex": 25,
    "artist": "UZI-LAY",
    "series": "2ndMIX",
    "minBPM": 120,
    "maxBPM": 120,
    "version": 20190320
  },
  {
    "id": "IQqOIb6ob8bIbOII66ID0oIQDPl6bdbb",
    "name": "PUT YOUR FAITH IN ME (Jazzy Groove)",
    "nameKana": "PUT YOUR FAITH IN ME JAZZY GROOVE",
    "nameIndex": 25,
    "artist": "UZI-LAY",
    "series": "2ndMIX",
    "minBPM": 120,
    "maxBPM": 120,
    "version": 20190320
  },
  {
    "id": "1P9qQdiiodODqQPl0OO88iiiqdoDIPO6",
    "name": "SP-TRIP MACHINE～JUNGLE MIX～",
    "nameKana": "SP TRIP MACHINE JUNGLE MIX",
    "nameIndex": 28,
    "artist": "DE-SIRE",
    "series": "2ndMIX",
    "minBPM": 160,
    "maxBPM": 160,
    "version": 20190320
  }
]
