=== ddradar/ddradar-old/static/chart-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://ddradar.app/chart-schema.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "Step Chart Info",
    "required": [
      "songId",
      "songName",
      "playStyle",
      "difficulty",
      "level",
      "notes",
      "freezeArrow",
      "shockArrow",
      "stream",
      "voltage",
      "air",
      "freeze",
      "chaos",
      "version"
    ],
    "properties": {
      "songId": {
        "$id": "#/items/properties/songId",
        "type": "string",
        "minLength": 32,
        "maxLength": 32,
        "title": "Song's Id",
        "examples": ["lqI8DD9Plq6IO8P8P6Pl8Di98DlI9oP8"],
        "pattern": "^(.*)$"
      },
      "songName": {
        "$id": "#/items/properties/songName",
        "type": "string",
        "title": "Song Name",
        "pattern": "^(.*)$"
      },
      "playStyle": {
        "$id": "#/items/properties/playStyle",
        "type": "integer",
        "title": "Play Style (SP:1 DP:2)",
        "enum": [1, 2]
      },
      "difficulty": {
        "$id": "#/items/properties/difficulty",
        "type": "integer",
        "title": "Difficulty (BEGINNER:0, BASIC:1, ..., CHALLENGE:4)",
        "enum": [0, 1, 2, 3, 4]
      },
      "level": {
        "$id": "#/items/properties/level",
        "type": "integer",
        "title": "Chart Level",
        "exclusiveMinimum": 0,
        "maximum": 19
      },
      "notes": {
        "$id": "#/items/properties/notes",
        "type": "integer",
        "title": "Normal Arrow's count (Jump = 1 count)",
        "exclusiveMinimum": 0
      },
      "freezeArrow": {
        "$id": "#/items/properties/freezeArrow",
        "type": "integer",
        "title": "Freeze Arrow's count",
        "minimum": 0
      },
      "shockArrow": {
        "$id": "#/items/properties/shockArrow",
        "type": "integer",
        "title": "Shock Arrow's count",
        "minimum": 0,
        "default": 0
      },
      "stream": {
        "$id": "#/items/properties/stream",
        "type": "integer",
        "title": "Groove Radar STREAM",
        "exclusiveMinimum": 0
      },
      "voltage": {
        "$id": "#/items/properties/voltage",
        "type": "integer",
        "title": "Groove Radar VOLTAGE",
        "exclusiveMinimum": 0
      },
      "air": {
        "$id": "#/items/properties/air",
        "type": "integer",
        "title": "Groove Radar AIR",
        "minimum": 0
      },
      "freeze": {
        "$id": "#/items/properties/freeze",
        "type": "integer",
        "title": "Groove Radar FREEZE",
        "minimum": 0,
        "default": 0
      },
      "chaos": {
        "$id": "#/items/properties/chaos",
        "type": "integer",
        "title": "Groove Radar CHAOS",
        "minimum": 0,
        "default": 0
      },
      "version": {
        "$id": "#/items/properties/version",
        "type": "integer",
        "title": "Use for diff update. if you change or create data, increase its version."
      }
    }
  }
}

=== ddradar/ddradar-old/song-info/data/charts/chart-1st.json
[
  {
    "songId": "8Il6980di8P89lil1PDIqqIbiq1QO8lQ",
    "songName": "MAKE IT BETTER",
    "playStyle": 1,
    "difficulty": 0,
    "level": 3,
    "notes": 67,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 14,
    "voltage": 14,
    "air": 9,
    "freeze": 0,
    "chaos": 0,
    "version": 20191109
  },
  {
    "songId": "8Il6980di8P89lil1PDIqqIbiq1QO8lQ",
    "songName": "MAKE IT BETTER",
    "playStyle": 1,
    "difficulty": 1,
    "level": 7,
    "notes": 143,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 31,
    "voltage": 29,
    "air": 47,
    "freeze": 0,
    "chaos": 3,
    "version": 20191109
  },
  {
    "songId": "8Il6980di8P89lil1PDIqqIbiq1QO8lQ",
    "songName": "MAKE IT BETTER",
    "playStyle": 1,
    "difficulty": 2,
    "level": 9,
    "notes": 188,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 41,
    "voltage": 39,
    "air": 27,
    "freeze": 0,
    "chaos": 13,
    "version": 20191109
  },
  {
    "songId": "8Il6980di8P89lil1PDIqqIbiq1QO8lQ",
    "songName": "MAKE IT BETTER",
    "playStyle": 1,
    "difficulty": 3,
    "level": 12,
    "notes": 212,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 46,
    "voltage": 39,
    "air": 54,
    "freeze": 0,
    "chaos": 19,
    "version": 20191109
  },
  {
    "songId": "8Il6980di8P89lil1PDIqqIbiq1QO8lQ",
    "songName": "MAKE IT BETTER",
    "playStyle": 2,
    "difficulty": 1,
    "level": 7,
    "notes": 130,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 28,
    "voltage": 29,
    "air": 61,
    "freeze": 0,
    "chaos": 1,
    "version": 20191109
  },
  {
    "songId": "8Il6980di8P89lil1PDIqqIbiq1QO8lQ",
    "songName": "MAKE IT BETTER",
    "playStyle": 2,
    "difficulty": 2,
    "level": 9,
    "notes": 181,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 40,
    "voltage": 39,
    "air": 30,
    "freeze": 0,
    "chaos": 11,
    "version": 20191109
  },
  {
    "songId": "8Il6980di8P89lil1PDIqqIbiq1QO8lQ",
    "songName": "MAKE IT BETTER",
    "playStyle": 2,
    "difficulty": 3,
    "level": 11,
    "notes": 220,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 48,
    "voltage": 54,
    "air": 27,
    "freeze": 0,
    "chaos": 41,
    "version": 20191109
  },
  {
    "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
    "songName": "PARANOiA",
    "playStyle": 1,
    "difficulty": 0,
    "level": 4,
    "notes": 138,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 29,
    "voltage": 22,
    "air": 5,
    "freeze": 0,
    "chaos": 0,
    "version": 20191109
  },
  {
    "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
    "songName": "PARANOiA",
    "playStyle": 1,
    "difficulty": 1,
    "level": 8,
    "notes": 264,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 56,
    "voltage": 44,
    "air": 18,
    "freeze": 0,
    "chaos": 4,
    "version": 20191109
  },
  {
    "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
    "songName": "PARANOiA",
    "playStyle": 1,
    "difficulty": 2,
    "level": 9,
    "notes": 275,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 58,
    "voltage": 52,
    "air": 49,
    "freeze": 0,
    "chaos": 6,
    "version": 20191109
  },
  {
    "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
    "songName": "PARANOiA",
    "playStyle": 1,
    "difficulty": 3,
    "level": 11,
    "notes": 319,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 67,
    "voltage": 52,
    "air": 25,
    "freeze": 0,
    "chaos": 17,
    "version": 20191109
  },
  {
    "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
    "songName": "PARANOiA",
    "playStyle": 2,
    "difficulty": 1,
    "level": 8,
    "notes": 254,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 54,
    "voltage": 37,
    "air": 61,
    "freeze": 0,
    "chaos": 2,
    "version": 20191109
  },
  {
    "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
    "songName": "PARANOiA",
    "playStyle": 2,
    "difficulty": 2,
    "level": 13,
    "notes": 309,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 65,
    "voltage": 60,
    "air": 56,
    "freeze": 0,
    "chaos": 13,
    "version": 20191109
  },
  {
    "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
    "songName": "PARANOiA",
    "playStyle": 2,
    "difficulty": 3,
    "level": 11,
    "notes": 382,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 81,
    "voltage": 60,
    "air": 60,
    "freeze": 0,
    "chaos": 31,
    "version": 20191109
  },
  {
    "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
    "songName": "TRIP MACHINE",
    "playStyle": 1,
    "difficulty": 0,
    "level": 3,
    "notes": 106,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 25,
    "voltage": 26,
    "air": 5,
    "freeze": 0,
    "chaos": 0,
    "version": 20191109
  },
  {
    "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
    "songName": "TRIP MACHINE",
    "playStyle": 1,
    "difficulty": 1,
    "level": 8,
    "notes": 191,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 47,
    "voltage": 40,
    "air": 14,
    "freeze": 0,
    "chaos": 4,
    "version": 20191109
  },
  {
    "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
    "songName": "TRIP MACHINE",
    "playStyle": 1,
    "difficulty": 2,
    "level": 9,
    "notes": 211,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 52,
    "voltage": 40,
    "air": 30,
    "freeze": 0,
    "chaos": 7,
    "version": 20191109
  },
  {
    "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
    "songName": "TRIP MACHINE",
    "playStyle": 1,
    "difficulty": 3,
    "level": 10,
    "notes": 230,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 56,
    "voltage": 53,
    "air": 36,
    "freeze": 0,
    "chaos": 12,
    "version": 20191109
  },
  {
    "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
    "songName": "TRIP MACHINE",
    "playStyle": 2,
    "difficulty": 1,
    "level": 9,
    "notes": 201,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 49,
    "voltage": 40,
    "air": 27,
    "freeze": 0,
    "chaos": 3,
    "version": 20191109
  },
  {
    "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
    "songName": "TRIP MACHINE",
    "playStyle": 2,
    "difficulty": 2,
    "level": 10,
    "notes": 215,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 53,
    "voltage": 53,
    "air": 34,
    "freeze": 0,
    "chaos": 7,
    "version": 20191109
  },
  {
    "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
    "songName": "TRIP MACHINE",
    "playStyle": 2,
    "difficulty": 3,
    "level": 10,
    "notes": 264,
    "freezeArrow": 0,
    "shockArrow": 0,
    "stream": 65,
    "voltage": 53,
    "air": 27,
    "freeze": 0,
    "chaos": 25,
    "version": 20191109
  }
]
