=== ddradar/ddradar-old/static/cource-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://ddradar.app/cource-schema.json",
  "definitions": {
    "id": {
      "type": "string",
      "minLength": 32,
      "maxLength": 32,
      "examples": ["b1do8OI6qDDlQO0PI16868ql6bdbI886"],
      "pattern": "^([01689bdiloqDIOPQ]*)$"
    },
    "playStyle": {
      "type": "integer",
      "title": "Play Style (SP:1 DP:2)",
      "enum": [1, 2]
    },
    "difficulty": {
      "type": "integer",
      "title": "Difficulty (BEGINNER:0, BASIC:1, ..., CHALLENGE:4)",
      "enum": [0, 1, 2, 3, 4]
    },
    "level": {
      "type": "integer",
      "exclusiveMinimum": 0,
      "maximum": 19
    }
  },
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "type": "object",
    "title": "Cource Info",
    "required": [
      "id",
      "name",
      "orders",
      "version"
    ],
    "properties": {
      "id": {
        "$ref": "#/definitions/id",
        "title": "Cource's Id"
      },
      "name": {
        "type": "string",
        "title": "Cource Name"
      },
      "orders": {
        "type": "array",
        "title": "Cource Orders",
        "items": {
          "type": "object",
          "title": "Cource Order Info",
          "required": [
            "playStyle",
            "difficulty",
            "level",
            "chartOrder"
          ],
          "properties": {
            "playStyle": {
              "$ref": "#/definitions/playStyle"
            },
            "difficulty": {
              "$ref": "#/definitions/difficulty"
            },
            "level": {
              "$ref": "#/definitions/level",
              "title": "Cource Level (often the maximum level of chartOrders)"
            },
            "chartOrder": {
              "type": "array",
              "title": "",
              "items": {
                "type": "object",
                "title": "Step Chart Info",
                "required": [
                  "songId",
                  "songName",
                  "playStyle",
                  "difficulty",
                  "level"
                ],
                "properties": {
                  "songId": {
                    "$ref": "#/definitions/id",
                    "title": "Song's Id"
                  },
                  "songName": {
                    "type": "string",
                    "title": "Song Name"
                  },
                  "playStyle": {
                    "$ref": "#/definitions/playStyle"
                  },
                  "difficulty": {
                    "$ref": "#/definitions/difficulty"
                  },
                  "level": {
                    "$ref": "#/definitions/level",
                    "title": "Chart Level"
                  }
                }
              }
            }
          }
        }
      },
      "version": {
        "type": "integer",
        "title": "Use for diff update. if you change or create data, increase its version."
      }
    }
  }
}

=== ddradar/ddradar-old/static/cource.json
[
  {
    "id": "qbbOOO1QibO1861bqQII9lqlPiIoqb98",
    "name": "FIRST",
    "version": 20190328,
    "orders": [
      {
        "playStyle": 1,
        "difficulty": 0,
        "level": 4,
        "chartOrder": [
          {
            "songId": "lIlQ8DbPP6Iil1DOlQ6d8IPQblDQ8IiI",
            "songName": "HAVE YOU NEVER BEEN MELLOW (20th Anniversary Mix)",
            "playStyle": 1,
            "difficulty": 0,
            "level": 2
          },
          {
            "songId": "b1do8OI6qDDlQO0PI16868ql6bdbI886",
            "songName": "MAKE IT BETTER",
            "playStyle": 1,
            "difficulty": 0,
            "level": 3
          },
          {
            "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
            "songName": "TRIP MACHINE",
            "playStyle": 1,
            "difficulty": 0,
            "level": 3
          },
          {
            "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
            "songName": "PARANOiA",
            "playStyle": 1,
            "difficulty": 0,
            "level": 4
          }
        ]
      },
      {
        "playStyle": 1,
        "difficulty": 1,
        "level": 8,
        "chartOrder": [
          {
            "songId": "lIlQ8DbPP6Iil1DOlQ6d8IPQblDQ8IiI",
            "songName": "HAVE YOU NEVER BEEN MELLOW (20th Anniversary Mix)",
            "playStyle": 1,
            "difficulty": 1,
            "level": 4
          },
          {
            "songId": "b1do8OI6qDDlQO0PI16868ql6bdbI886",
            "songName": "MAKE IT BETTER",
            "playStyle": 1,
            "difficulty": 1,
            "level": 7
          },
          {
            "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
            "songName": "TRIP MACHINE",
            "playStyle": 1,
            "difficulty": 1,
            "level": 8
          },
          {
            "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
            "songName": "PARANOiA",
            "playStyle": 1,
            "difficulty": 1,
            "level": 8
          }
        ]
      },
      {
        "playStyle": 1,
        "difficulty": 2,
        "level": 9,
        "chartOrder": [
          {
            "songId": "lIlQ8DbPP6Iil1DOlQ6d8IPQblDQ8IiI",
            "songName": "HAVE YOU NEVER BEEN MELLOW (20th Anniversary Mix)",
            "playStyle": 1,
            "difficulty": 2,
            "level": 6
          },
          {
            "songId": "b1do8OI6qDDlQO0PI16868ql6bdbI886",
            "songName": "MAKE IT BETTER",
            "playStyle": 1,
            "difficulty": 2,
            "level": 9
          },
          {
            "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
            "songName": "TRIP MACHINE",
            "playStyle": 1,
            "difficulty": 2,
            "level": 9
          },
          {
            "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
            "songName": "PARANOiA",
            "playStyle": 1,
            "difficulty": 2,
            "level": 9
          }
        ]
      },
      {
        "playStyle": 1,
        "difficulty": 3,
        "level": 12,
        "chartOrder": [
          {
            "songId": "lIlQ8DbPP6Iil1DOlQ6d8IPQblDQ8IiI",
            "songName": "HAVE YOU NEVER BEEN MELLOW (20th Anniversary Mix)",
            "playStyle": 1,
            "difficulty": 3,
            "level": 10
          },
          {
            "songId": "b1do8OI6qDDlQO0PI16868ql6bdbI886",
            "songName": "MAKE IT BETTER",
            "playStyle": 1,
            "difficulty": 3,
            "level": 12
          },
          {
            "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
            "songName": "TRIP MACHINE",
            "playStyle": 1,
            "difficulty": 3,
            "level": 10
          },
          {
            "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
            "songName": "PARANOiA",
            "playStyle": 1,
            "difficulty": 3,
            "level": 11
          }
        ]
      },
      {
        "playStyle": 2,
        "difficulty": 1,
        "level": 9,
        "chartOrder": [
          {
            "songId": "lIlQ8DbPP6Iil1DOlQ6d8IPQblDQ8IiI",
            "songName": "HAVE YOU NEVER BEEN MELLOW (20th Anniversary Mix)",
            "playStyle": 2,
            "difficulty": 1,
            "level": 4
          },
          {
            "songId": "b1do8OI6qDDlQO0PI16868ql6bdbI886",
            "songName": "MAKE IT BETTER",
            "playStyle": 2,
            "difficulty": 1,
            "level": 7
          },
          {
            "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
            "songName": "TRIP MACHINE",
            "playStyle": 2,
            "difficulty": 1,
            "level": 9
          },
          {
            "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
            "songName": "PARANOiA",
            "playStyle": 2,
            "difficulty": 1,
            "level": 8
          }
        ]
      },
      {
        "playStyle": 2,
        "difficulty": 2,
        "level": 13,
        "chartOrder": [
          {
            "songId": "lIlQ8DbPP6Iil1DOlQ6d8IPQblDQ8IiI",
            "songName": "HAVE YOU NEVER BEEN MELLOW (20th Anniversary Mix)",
            "playStyle": 2,
            "difficulty": 2,
            "level": 6
          },
          {
            "songId": "b1do8OI6qDDlQO0PI16868ql6bdbI886",
            "songName": "MAKE IT BETTER",
            "playStyle": 2,
            "difficulty": 2,
            "level": 9
          },
          {
            "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
            "songName": "TRIP MACHINE",
            "playStyle": 2,
            "difficulty": 2,
            "level": 10
          },
          {
            "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
            "songName": "PARANOiA",
            "playStyle": 2,
            "difficulty": 2,
            "level": 13
          }
        ]
      },
      {
        "playStyle": 2,
        "difficulty": 3,
        "level": 11,
        "chartOrder": [
          {
            "songId": "lIlQ8DbPP6Iil1DOlQ6d8IPQblDQ8IiI",
            "songName": "HAVE YOU NEVER BEEN MELLOW (20th Anniversary Mix)",
            "playStyle": 2,
            "difficulty": 3,
            "level": 10
          },
          {
            "songId": "b1do8OI6qDDlQO0PI16868ql6bdbI886",
            "songName": "MAKE IT BETTER",
            "playStyle": 2,
            "difficulty": 3,
            "level": 11
          },
          {
            "songId": "Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi",
            "songName": "TRIP MACHINE",
            "playStyle": 2,
            "difficulty": 3,
            "level": 10
          },
          {
            "songId": "06loOQ0DQb0DqbOibl6qO81qlIdoP9DI",
            "songName": "PARANOiA",
            "playStyle": 2,
            "difficulty": 3,
            "level": 11
          }
        ]
      }
    ]
  },
  {
    "id": "I90bQ81P1blOPIdd9PPl6I9D8DQ1dIob",
    "name": "TWENTY",
    "version": 20190328,
    "orders": [
      {
        "playStyle": 1,
        "difficulty": 0,
        "level": 4,
        "chartOrder": [
          {
            "songId": "PdPdbdQ1lDI18O90Q0li8QI0bo99bidd",
            "songName": "This Beat Is.....",
            "playStyle": 1,
            "difficulty": 0,
            "level": 1
          },
          {
            "songId": "PPQb966D6Ql6Q8iPo68810PdDiI6D0bl",
            "songName": "Waiting",
            "playStyle": 1,
            "difficulty": 0,
            "level": 3
          },
          {
            "songId": "6iO8d9ld00I6lDIO6qbOldP99oqloqb9",
            "songName": "Dead Heat",
            "playStyle": 1,
            "difficulty": 0,
            "level": 4
          },
          {
            "songId": "1iDPo19Pb9ooi8OqiidbqPb06DDdqiqo",
            "songName": "Neverland",
            "playStyle": 1,
            "difficulty": 0,
            "level": 4
          }
        ]
      },
      {
        "playStyle": 1,
        "difficulty": 1,
        "level": 8,
        "chartOrder": [
          {
            "songId": "PdPdbdQ1lDI18O90Q0li8QI0bo99bidd",
            "songName": "This Beat Is.....",
            "playStyle": 1,
            "difficulty": 1,
            "level": 4
          },
          {
            "songId": "PPQb966D6Ql6Q8iPo68810PdDiI6D0bl",
            "songName": "Waiting",
            "playStyle": 1,
            "difficulty": 1,
            "level": 6
          },
          {
            "songId": "6iO8d9ld00I6lDIO6qbOldP99oqloqb9",
            "songName": "Dead Heat",
            "playStyle": 1,
            "difficulty": 1,
            "level": 6
          },
          {
            "songId": "1iDPo19Pb9ooi8OqiidbqPb06DDdqiqo",
            "songName": "Neverland",
            "playStyle": 1,
            "difficulty": 1,
            "level": 8
          }
        ]
      },
      {
        "playStyle": 1,
        "difficulty": 2,
        "level": 12,
        "chartOrder": [
          {
            "songId": "PdPdbdQ1lDI18O90Q0li8QI0bo99bidd",
            "songName": "This Beat Is.....",
            "playStyle": 1,
            "difficulty": 2,
            "level": 7
          },
          {
            "songId": "PPQb966D6Ql6Q8iPo68810PdDiI6D0bl",
            "songName": "Waiting",
            "playStyle": 1,
            "difficulty": 2,
            "level": 10
          },
          {
            "songId": "6iO8d9ld00I6lDIO6qbOldP99oqloqb9",
            "songName": "Dead Heat",
            "playStyle": 1,
            "difficulty": 2,
            "level": 10
          },
          {
            "songId": "1iDPo19Pb9ooi8OqiidbqPb06DDdqiqo",
            "songName": "Neverland",
            "playStyle": 1,
            "difficulty": 2,
            "level": 12
          }
        ]
      },
      {
        "playStyle": 1,
        "difficulty": 3,
        "level": 15,
        "chartOrder": [
          {
            "songId": "PdPdbdQ1lDI18O90Q0li8QI0bo99bidd",
